import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import '../theme/app_theme.dart';

class ApprovalScreen extends StatefulWidget {
  const ApprovalScreen({super.key});

  @override
  State<ApprovalScreen> createState() => _ApprovalScreenState();
}

class _ApprovalScreenState extends State<ApprovalScreen> {
  List<dynamic> _pendingActions = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _fetchPendingActions();
  }

  // 1. FETCH REAL DATABASE DRAFTS
  Future<void> _fetchPendingActions() async {
    setState(() => _isLoading = true);
    try {
      final response = await http.get(Uri.parse('http://127.0.0.1:8080/api/actions/pending/aqil_01'));
      if (response.statusCode == 200) {
        setState(() {
          _pendingActions = jsonDecode(response.body);
          _isLoading = false;
        });
      } else {
        setState(() => _isLoading = false);
      }
    } catch (e) {
      setState(() => _isLoading = false);
    }
  }

  // 2. SEND DECISION TO SPRING BOOT
  Future<void> _submitDecision(int actionId, String decision) async {
    try {
      await http.post(
        Uri.parse('http://127.0.0.1:8080/api/actions/$actionId/decision'),
        headers: {"Content-Type": "application/json"},
        body: jsonEncode({"userId": "aqil_01", "decision": decision}),
      );
      _fetchPendingActions(); // Refresh the list after transaction
    } catch (e) {
      print("TRANSACTION ERROR: $e");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.bg,
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _pendingActions.isEmpty
          ? _buildEmptyState()
          : RefreshIndicator(
        onRefresh: _fetchPendingActions,
        child: ListView.builder(
          padding: const EdgeInsets.all(16),
          itemCount: _pendingActions.length,
          itemBuilder: (context, index) {
            return _buildApprovalCard(_pendingActions[index]);
          },
        ),
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(color: AppColors.success.withValues(alpha: 0.1), shape: BoxShape.circle),
            child: const Icon(Icons.task_alt_rounded, color: AppColors.success, size: 48),
          ),
          const SizedBox(height: 16),
          const Text('Zero-Trust Queue Clear', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.white)),
          const SizedBox(height: 8),
          const Text('No backend transactions pending.', style: TextStyle(color: Colors.grey)),
        ],
      ),
    );
  }

  Widget _buildApprovalCard(Map<String, dynamic> action) {
    // Parse the strict JSON payload generated by the AI
    Map<String, dynamic> payload = jsonDecode(action['payload']);

    return Card(
      color: AppColors.surface,
      margin: const EdgeInsets.only(bottom: 16),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: const BorderSide(color: AppColors.border),
      ),
      child: Padding(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Icon(Icons.security_rounded, color: AppColors.warning, size: 24),
                const SizedBox(width: 12),
                Expanded(
                    child: Text(
                        "Source: ${action['toolName']}",
                        style: const TextStyle(color: Colors.white, fontSize: 14, fontWeight: FontWeight.w600)
                    )
                ),
              ],
            ),
            const Divider(height: 30, color: AppColors.border),

            // Dynamically render the parsed AI arguments
            ...payload.entries.map((e) => Padding(
              padding: const EdgeInsets.symmetric(vertical: 4.0),
              child: Text("${e.key.toUpperCase()}: ${e.value}", style: const TextStyle(color: AppColors.textSecondary, fontSize: 14)),
            )),

            const SizedBox(height: 16),
            Text(
                "Deduction: PKR ${action['cost']}",
                style: const TextStyle(color: AppColors.primary, fontSize: 20, fontWeight: FontWeight.bold)
            ),
            const SizedBox(height: 20),

            Row(
              children: [
                Expanded(
                  child: OutlinedButton(
                    onPressed: () => _submitDecision(action['id'], "REJECT"),
                    style: OutlinedButton.styleFrom(
                        side: const BorderSide(color: AppColors.danger),
                        foregroundColor: AppColors.danger
                    ),
                    child: const Text("Block"),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: ElevatedButton(
                    onPressed: () => _submitDecision(action['id'], "APPROVE"),
                    style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.success,
                        foregroundColor: Colors.white
                    ),
                    child: const Text("Authorize"),
                  ),
                ),
              ],
            )
          ],
        ),
      ),
    );
  }
}